### PR TITLE
Add pinning functionality

### PR DESCRIPTION
**Pull request by ipostanogov**
Sometimes it is really annoying when expanding a node rearranges the whole graph. This patch allows to pin the current nodes.

### CODE REVIEW

**Comment by johardi** [comment]
Hi Igor,
thank you for your excellent contribution. I've tested the feature and it worked as you described. But I have a minor input to perfect the UI. It might look better if the users can see a UI feedback when they press the 'pin/unpin' button. Right now it is unclear if the graph is pinned or unpinned using the current button UI. 

You can see the examples from the existing toggle buttons like 'Node Types', 'Arc Types' or 'Pin Node Tooltips'.

**Comment by ipostanogov** [comment]
Hi Josef,
thanks for your review. I have thought about this approach. But what if a user had pinned some nodes, expanded some of them, and want to pin the current nodes again? Should he/she press on the already toggled button but the button should keep the toggle state?

**Comment by csnyulas** [comment]
I've also looked at the new feature together with Josef. My impression was that once you click on the "pin nodes' location" button, basically all the nodes in the currently displayed layout will be "pinned", i.e. they won't change position on subsequent actions, unless you manually move them. If you double click on a node, to expand its subclasses, the newly displayed subclasses will be arranged nicely conform to the latest layout selection, but the class itself will not change its position, nor will the other, previously displayed classes. So in this sense I think the toggle button behaviour, is quite appropriate. If the button is pressed, than there will be no automatic rearrangement of the nodes. If you un-click it, the nodes (all of them) will be automatically rearranged based on the selected layout. Or did you have a different behaviour in mind (for example, to "pin" only the nodes that had their location explicitly changed by the user)?

**Comment by ipostanogov** [comment]
Here is an example. We have
- `Person`
  - `Employee`
    - `AcademicStaff`
  - `Student`
    - `Graduate`

I add `Person` to the graph and click on the pin button. The location of `Person` is fixed. Then I expand it (now I see `Person`, `Employee`, `Student`) and arrange the new nodes manually. Now I want to expand `Student`, but keep the all current nodes' locations. If we use a toggle button, then the pin button will be already toggled.

Pressing the pin button represents the intention to fix the current nodes' locations. It could be pressed multiple times. As you've already said, the unpin button automatically rearranges based on the selected layout.

**Comment by csnyulas** [comment]
If I understand correctly, what you describe is consistent with what I observed.

Basically once the user pressed the pin button, he will go into "manual" arranging mode. Everything will stay where he or she places it. There is no need to press the pin button again. If we make the "pin" button a toggle button, pressing it again would set the layout back to "automatic" mode. If you think it would be helpful, you may prevent the rearrangement of the layout right after the pin button is unchecked, so that only on subsequent node generating actions (such as expanding a node) would the layout be rearranged.
If you wish to implement a selective pinning of nodes, that would be more difficult, I think, and the algorithm that automatically generates layout may be a bit confused when it needs to do it for some nodes but not others, especially that there may exist a very complex network of relations between the pinned and unpinned nodes. Selecting the nodes that you want to pin, and showing which nodes are already pinned would also complicate both the code and the user interactions.

**Comment by ipostanogov** [comment]
Looks like you are thinking about the button I have implemented as a switcher between automatic and manual arranging modes. It is wrong.

Real life example: I had been preparing a figure for the publication. I had added 7 nodes to the graph and rearranged them manually. Then I had understood that I would need to expand a node to show it's descendants (9 nodes total). In the current version of Protégé, the whole graph will be rearranged and I will have to place the 7 original nodes to the places that I want. Again. With this patch I can say "do not change the current nodes' location, help me with the places of the new nodes only". And, yes, I want to do it multiple times during the figure's preparation.

**Comment by johardi** [comment]
Hi Igor,
thanks for the explanation. So the function actually can pin each node individually? I might have missed that and if so then I found a bug.

Here are the steps to reproduce using your example:
1. I started by opening the tree and had only `owl:Thing`, `Person`, `Employee` and `Student` visible,
2. I rearranged their positions anywhere inside the view,
3. I pinned the `Employee`,
4. I expanded the `Employee` to see the subclass (i.e., `AcademicStaff`).

My assumption would be to have only the `Employee` got pinned but I found that all of the class nodes are pinned (well, except the `AcademicStaff`). 

Did you get the same result? And whether this is an expected behavior?

**Comment by ipostanogov** [comment]
Hi Josef,
it is an expected behavior. As you can see in the [code](https://github.com/protegeproject/ca.uvic.cs.chisel.cajun/pull/2/commits/48637aff0dceeb3a2d5b9eaa019d7f63d0a27973), pinning applies to all nodes. I don't think there is a big need for pinning each node individually. The idea is to fix the current state of the graph.

**Comment by johardi** [comment]
Hi Igor,
I think I finally get your point. Your last comment really helps. I'm sorry it takes a while for me to digest all the info here. OK I think I'll do the merge in the few hours.

As for the UI improvement we can try to come up with a better idea in the next commit. I still would like to see some sort of UI feedback when users click the pin/unpin button. One idea might be to highlight the nodes border when pinned and clear them when unpinned. That said, feel free to make your own idea later on. All good!

**Comment by csnyulas** [comment]
@ipostanogov So far I think we agree that the following is the expected and actual behavior (please confirm):
(1) if you press the "pin nodes" button, the position of all nodes in the current graph are "frozen". That is, if you expand one of the nodes, the NEW nodes will be displayed in some automatically decided locations, but all the pre-existing nodes will stay where they were before the expansion.

The question is what should happen when you expand in a second step one of the new nodes (or even the original nodes), WITHOUT pressing a second time on the "pin nodes"  button?
This is what I observe:
(2) all the nodes stay where they are, including a) the ones that you arranged prior to pressing on the "pin" button the first time, b) the nodes that you moved between the first and the second expansion, and c) the nodes that where laid out automatically as result of the first expansion, but which you did not move.
From your messages, I understand that this is the expected behaviour. Please confirm.

If this is true (i.e. that the nodes are all staying in the same place at subsequent expansions), then why would you ever need to press the "pin nodes" button the second time? UNLESS you choose an automatic layout clicking on one of the other layout buttons, OR "unpin the nodes" (which will result in automatic layout of all the nodes, at least during subsequent expansions), you would not need to "pin" your nodes again, because they all are pinned already. Do you agree?

**Comment by ipostanogov** [comment]
@csnyulas 
Here is an example with [SWRC ontology](http://ontoware.org/swrc/swrc/SWRCOWL/swrc_updated_v0.7.1.owl). Expand `owl:Thing`, pin, expand `Document`, expand `Product`. The positions of `Publication` and `Unpublished` have changed (2c in your example is not true):
before
after without pinning
If I press pin _again_ after expanding `Document`, I will save their positions (and then move only `SoftwareComponent` to the place I want):
after with pinning

**Comment by ipostanogov** [comment]
I have also checked the `GraphNode.setFixedLocation` usage. Look like you will need to restore the previous fixing states in one of the methods of [OntoGraf code](https://github.com/protegeproject/ontograf/blob/master/src/main/java/org/protege/ontograf/common/GraphController.java#L233-L236) (now it unpins all the nodes).

**Comment by csnyulas** [comment]
Thank you @ipostanogov This illustration is very helpful. I can see now that after a pin all new nodes are "mobile" and can be rearranged by the layout algorithm in different ways, unless they have been pinned with a subsequent button press. I have to apologize, for not observing this behaviour when I tried it out.
In this case, I have to agree with Josef, that we should somehow visually highlight (e.g. with a little pin icon in the upper right corner) which nodes are pinned and which ones are not, otherwise the user might find the behaviour quite confusing (as our lengthy discussion on trying to understand what it does and what it suppose to do, proves it).

Thanks again for your contribution and patience!

**Comment by ipostanogov** [comment]
I am absolutely agree that there is a need for visually highlight, but I have no experience with piccolo2d and it would take a significant amount of time for me to add this icon and debug it. I think that you will do it much better (and faster).

You are welcome!

**Pull request merged**
